name: Build and Deploy

on: 
  push:
    branches:
      - "main"
  pull_request:
    branches:
      - "main"

env: 
  CNAME_PATH: "./CNAME"

jobs:
  test: 
    runs-on: ubuntu-latest
    steps:
      - name: pulling git repo
        uses: actions/checkout@v2
      - name: test
        run: |
          echo "test"
  deploy: 
    needs: [test]
    runs-on: ubuntu-latest
    steps:
      - name: pulling git repo
        uses: actions/checkout@v2
      - name: build
        run: |
          npm install
          npm run build
          cp $CNAME_PATH build
      - name: deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build




