name: Build and Deploy

on: 
  push:
    branches:
      - "main"
  pull_request:
    branches:
      - "main"

env: 
  CNAME_PATH: "./CNAME"

jobs:
  test: 
    runs-on: ubuntu-latest
    steps:
      - name: pulling git repo
        uses: actions/checkout@v2
      - name: test
        run: |
          echo "test"
  build: 
    needs: [test]
    runs-on: ubuntu-latest
    steps:
      - name: pulling git repo
        uses: actions/checkout@v2
      - name: exmaple build image
        run: |
          echo "build"
  deploy: 
    needs: [test, build]
    runs-on: ubuntu-latest
    steps:
      - name: pulling git repo
        uses: actions/checkout@v2
      # - name: config setting
      #   run: |
      #     git config --global credential.helper wincred
      #     git config --global user.email juroberttyb@gmail.com
      #     git config --global user.name 'juroberttyb'
      - name: install enviroment
        run: npm install
      - name: predeploy
        run: |
          npm run build
          cp $CNAME build
      - name: deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build
      # - name: deploy
      #   run: npm run deploy




