name: Build and Deploy

on: 
  push:
    branches:
      - "main"
  pull_request:
    branches:
      - "main"

# env: 
#   ssh-key-github: ${{secrets.SSH_KEY_GITHUB}}

jobs:
  test: 
    runs-on: ubuntu-latest
    steps:
      - name: pulling git repo
        uses: actions/checkout@v2
      - name: test
        run: |
          echo "test"
  build: 
    needs: [test]
    runs-on: ubuntu-latest
    steps:
      - name: pulling git repo
        uses: actions/checkout@v2
      - name: exmaple build image
        run: |
          echo "build"
  deploy: 
    needs: [test, build]
    runs-on: ubuntu-latest
    steps:
      - name: pulling git repo
        uses: actions/checkout@v2
      - name: deploy
        run: |
          git config --global user.email juroberttyb@gmail.com
          mkdir ~/.ssh
          echo ${{secrets.SSH_KEY_GITHUB}} > ~/.ssh/id_rsa
          npm install
          npm run deploy
          echo "deploy"




